name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # todos os dias à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Gerar cobrinha SVG
        uses: Platane/snk@v3
        with:
          github_user_name: caiodias2004
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit e push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: Atualiza animação da cobrinha
          add: 'dist/*.svg'

      - name: Publicar no branch `output`
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
